# docker-compose.yml
services:  
    
  jenkins:
    image: jenkins/jenkins:lts # Use the official Jenkins LTS image
    command: sh -c "git init && git config --global --add safe.directory /Root/DockerCompose" 
    privileged: true # Required for Docker-in-Docker functionality if building Docker images within Jenkins
    user: root # Run as root user inside the container for full permissions
    ports:
      - "8080:8080" # Jenkins web interface
      - "50000:50000" # Jenkins agent communication port
    volumes:
      - jenkins_home:/var/jenkins_home # Persistent storage for Jenkins data
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for Docker-in-Docker
      - /usr/local/bin/docker:/usr/local/bin/docker # Mount Docker binary for Docker-in-Docker
      - /home/EduardoCorrea82AzureUser:/Root #Root
    container_name: jenkins_master
    restart: unless-stopped # Ensure Jenkins restarts automatically
  
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html  
    container_name: nginx_container
    restart: unless-stopped # Ensure Jenkins restarts automatically

volumes:
  jenkins_home: # Define the named volume for Jenkins data
